---
title: "Taske 2 - talapia"
author: "Erica Bishop"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(janitor)
```

```{r}

us_talapia_imports <- read_csv(here("data", "us_tilapia_imports.csv"))

```
```{r}
us_talapia_tidy <- us_talapia_imports |> 
  pivot_longer(cols = -country, values_to = "annual_vol", names_to = "year") |> 
  mutate(year = as.numeric(year))

```

Now find the total US talapia imports by year

```{r}
yearly_talapia_tot <- us_talapia_tidy |> 
  group_by(year) |> 
  summarize(total_vol = sum(annual_vol, na.rm = TRUE))

```

graph a ggplot of total US tilapia imports

```{r}

ggplot(data = yearly_talapia_tot,
       aes(x = year,
           y = total_vol)) +
  geom_line(color = "darkcyan") +
  labs(
    x = "year",
    y = "total import volume (thousands of pounds)",
    title = "Annual US tilapia imports"
  )

```

```{r}
ggsave(here("figs", "total_annual_us_tilapia_imports.png"))
```

Now create a subset for Ecuador, Honduras, Costa Rica, an Mexico

```{r}

imports_ec_ho_co_mx <- us_talapia_tidy |> 
  group_by(country) |> 
  filter(country %in% c("Ecuador", "Honduras", "Costa Rica", "Mexico"))

```

Now create a ggplot graph of total US tilapia imports over time, for the four countriesin the subset

```{r}
ggplot(data = imports_ec_ho_co_mx,
       aes(x = year,
           y = annual_vol)) +
  geom_line(
    aes(color = country)
  )


```

```{r}
ggsave(here("figs", "imports_by_country_subset1.png"))
```





